# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/parallel-lint --exclude vendor .
      - run: ./vendor/bin/phpcs --standard=./ruleset.xml --extensions=php
      - run: ./vendor/bin/psalm
      - run: ./vendor/bin/phpunit --coverage-clover=var/coverage.xml
